#pragma config(Sensor, S1,     ultraSonic,     sensorEV3_Ultrasonic)
#pragma config(Sensor, S2,     lightSensor,    sensorEV3_Color)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void driveUntilBlack();

task main()
{
	driveUntilBlack();
}

void driveUntilBlack()
{
	while(getButtonPress(buttonEnter) == 0)
	{
		displayBigTextLine(5, "Enter to end");

		if (SensorValue(lightSensor) < 25)
		{
			setMotorSync(leftMotor, rightMotor, 0, 0);
			sleep(100);
		}
		else
		{
			setMotorSync(leftMotor, rightMotor, 0, 20);
		}
	}
}
