#pragma config(Sensor, S1,     ultraSonic,     sensorEV3_Ultrasonic)
#pragma config(Sensor, S2,     lightSensor,    sensorEV3_Color)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void getLightDark(int* light, int* dark);

task main()
{
	int light, dark, threshold;

	getLightDark(&light, &dark);

	threshold = (light + dark) / 2;

	while(1)
	{
		displayTextLine(4, "Light: %d, Dark: %d", light, dark);
		displayTextLine(5, "Threshold: %d", threshold);
	}

}


void getLightDark(int* light, int* dark)
{
	while (getButtonPress(buttonEnter) == 0)
	{
		displayTextLine(5, "Press middle button for light");
	}

	sleep(200);

	*light = SensorValue[lightSensor];


	while (getButtonPress(buttonEnter) == 0)
	{
		displayTextLine(5, "Press middle button for dark");
	}

	*dark = SensorValue[lightSensor];
}
