#pragma config(Sensor, S1,     ultraSonic,     sensorEV3_Ultrasonic)
#pragma config(Sensor, S2,     lightSensor,    sensorEV3_Color)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void lineTrack();
void avoidObstacle();
void reset();

task main()
{
	lineTrack();
}

void lineTrack()
{
	while(1)
	{
		// Exit program if enter is pressed
		displayBigTextLine(4, "Enter to end");
		if(getButtonPress(buttonEnter) == 1) stopAllTasks();

		if (getUSDistance(ultraSonic) < 10) avoidObstacle();

		// Turn left if dark detected, else turn right
		if(SensorValue(lightSensor) < 25)
		{
    	setMotorSync(leftMotor, rightMotor, -25, 25);
    }
    else
    {
    	setMotorSync(leftMotor, rightMotor, 25, 25);
    }
  }
}

void reset()
{
	resetMotorEncoder(leftMotor);
	resetMotorEncoder(rightMotor);
}

void avoidObstacle()
{
	// Turn left 90 degrees
	reset();
	setMotorSyncEncoder(leftMotor, rightMotor, -100, 180, 25);
	waitUntilMotorStop(leftMotor);

	setMotorSync(leftMotor, rightMotor, 0, 20);
	sleep(2000);

	// Turn right 90 degrees
	reset();
	setMotorSyncEncoder(leftMotor, rightMotor, 100, 180, 25);
	waitUntilMotorStop(leftMotor);

	setMotorSync(leftMotor, rightMotor, 0, 20);
	sleep(4000);

	// Turn right 90 degrees
	reset();
	setMotorSyncEncoder(leftMotor, rightMotor, 100, 180, 25);
	waitUntilMotorStop(leftMotor);

	setMotorSync(leftMotor, rightMotor, 0, 20);
	sleep(2000);

	// Turn left 90 degrees
	reset();
	setMotorSyncEncoder(leftMotor, rightMotor, -100, 180, 25);
	waitUntilMotorStop(leftMotor);
}

