#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch)
#pragma config(Sensor, S2,     gyroSensor,     sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S3,     colorSensor,    sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          armMotor,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
  // Turn 90 degrees to the right
	setMotorTarget(leftMotor, 180, 50);
	setMotorTarget(rightMotor, -180, 50);

	waitUntilMotorStop(leftMotor);
	waitUntilMotorStop(rightMotor);

	// Reset to 0 for sensors
	resetMotorEncoder(leftMotor);
	resetMotorEncoder(rightMotor);

	setMotorSpeed(leftMotor, 45);
  setMotorSpeed(rightMotor, 80);

  sleep(4250);


	setMotorSpeed(leftMotor, 80);
  setMotorSpeed(rightMotor, 45);

  sleep(4250);

  // Reset to 0 for sensors
	resetMotorEncoder(leftMotor);
	resetMotorEncoder(rightMotor);

  // Turn 90 degrees to the left
	setMotorTarget(leftMotor, -180, 50);
	setMotorTarget(rightMotor, 180, 50);

	waitUntilMotorStop(leftMotor);
	waitUntilMotorStop(rightMotor);

	// Reset to 0 for sensors
	resetMotorEncoder(leftMotor);
	resetMotorEncoder(rightMotor);

}
