#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch)
#pragma config(Sensor, S2,     gyroSensor,     sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S3,     colorSensor,    sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          armMotor,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*------------------------------------------------------------------------------------------------
  This program will move your robot make a series of moves for different lengths of time.
  At the end of the program, all motors will shut down automatically and turn off.

                            ROBOT CONFIGURATION: LEGO EV3 REM Bot
    MOTORS & SENSORS:
    [I/O Port]          [Name]              [Type]                [Description]
    MotorC        	leftMotor           LEGO EV3 Motor	  Left side motor
    MotorB       	rightMotor          LEGO EV3 Motor	  Right side motor (reversed)
------------------------------------------------------------------------------------------------*/

task main()
{
	// 1 meter divided by wheel circumfrance to find rotations needed
	float rotationsNeeded = 360 * (100 / 17.6);
	int count = 0;

	while(count < 4)
	{
		// Move forward for roughly a meter
		setMotorTarget(leftMotor, rotationsNeeded, 50);
		setMotorTarget(rightMotor, rotationsNeeded, 50);

		waitUntilMotorStop(leftMotor);
		waitUntilMotorStop(rightMotor);

		// Reset to 0 for sensors
		resetMotorEncoder(leftMotor);
		resetMotorEncoder(rightMotor);

		// Turn 90 degrees
		setMotorTarget(leftMotor, 180, 50);
		setMotorTarget(rightMotor, -180, 50);

		waitUntilMotorStop(leftMotor);
		waitUntilMotorStop(rightMotor);

		// Reset to 0 for sensors
		resetMotorEncoder(leftMotor);
		resetMotorEncoder(rightMotor);

		count = count + 1;
	}
}
