#pragma config(Sensor, S4,     gyroSensor,     sensorEV3_Gyro)
#pragma config(Motor,  motorA,          gyroMotor,     tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task gyroDrive();

task main()
{
	// Start gyro task
	startTask(gyroDrive);

	// Reset gyro sensor to 0
	resetGyro(gyroSensor);

	// While middle button has not been pressed
	while(getButtonPress(buttonEnter)== 0)
	{
		displayBigTextLine(5, "Enter to end");

		// Set Motor speed to gyro degrees divided by 2
		setMotorSync(leftMotor, rightMotor, 0, (getGyroDegrees(gyroSensor) / 2));
	}

	// End sub tasks at program end
	stopAllTasks();
}


// Oscillate the gyro from -45 degrees to + 45 degrees
task gyroDrive()
{
	// Infinite loop
	while(1)
	{
		// Reset motor and move to +45 degrees
		resetMotorEncoder(gyroMotor);
		setMotorTarget(gyroMotor, 90, 5);
		waitUntilMotorStop(gyroMotor);

		sleep(100);

		// Reset Motor and move to - 45 degrees
		resetMotorEncoder(gyroMotor);
		setMotorTarget(gyroMotor, -90, 5);
		waitUntilMotorStop(gyroMotor);
	}
}
